# Contenido para backend/docker-compose.yml
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=misis_dev
      - POSTGRES_USER=misis_user
      - POSTGRES_PASSWORD=misis_password
    ports:
      - "5432:5432"

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - docker/backend.env
    depends_on:
      - db

volumes:
  postgres_data:
